use Hicounselor;

select * from apps;

--the top 10 apps with the highest rating
select top 10
App,Rating
from apps order by Rating desc;

-- the top 5 most reviewed apps
SELECT TOP 5
    App,
    Reviews,
    Installs
FROM
    apps
ORDER BY
    Reviews DESC;

--the highest number of reviews and also retrieving the number of reviews and the category of the app
SELECT
    App,
    Reviews,
    Category
FROM
    apps
WHERE
    Reviews = (SELECT MAX(Reviews) FROM apps);

-- the total amount of revenue generated by the Google Play Store from hosting apps
SELECT
    SUM(Price) AS TotalRevenue
FROM
    apps
WHERE
    Type = 'Paid';

--the category of Google Play Store apps that has the highest number of installs and also determine the total number of installs for that particular category
SELECT
Top 1
    Category,
    SUM(Installs) AS TotalInstalls
FROM
    apps
GROUP BY
    Category
ORDER BY
    TotalInstalls DESC;


--the genre that has the most number of published apps
SELECT
TOP 1
    Genres,
    COUNT(*) AS AppCount
FROM
    apps
GROUP BY
    Genres
ORDER BY
    AppCount DESC;

--the list of all games ordered by the number of installs in descending order
SELECT
    App,
    Installs
FROM
    apps
WHERE
    Category = 'GAME'
ORDER BY
    Installs DESC;

-- the number of free and paid apps
SELECT
    COUNT(*) AS Total_Free_Apps,
    (SELECT COUNT(*) FROM apps WHERE Type = 'Paid') AS Total_Paid_Apps
FROM
    apps
WHERE
    Type = 'Free';


--the best dating app based on the highest number of reviews
SELECT
Top 1
    App,
    Reviews
FROM
    apps
WHERE
    Category = 'Dating'
ORDER BY
    Reviews DESC;


SELECT
    Sentiment AS Sentiment_Type,
    COUNT(*) AS Num_Reviews
FROM
    reviews
WHERE
    App = '10 best foods for You'
    AND (Sentiment = 'Positive' OR Sentiment = 'Negative')
GROUP BY
    Sentiment;

--the comments of ASUS SuperNote that have a sentiment polarity and sentiment subjectivity both equal to 1
SELECT
    Translated_Review
FROM
    reviews
WHERE
    App = 'ASUS SuperNote'
    AND Sentiment_Polarity = 1
    AND Sentiment_Subjectivity = 1;

--all the neutral sentiment reviews for the app "Abs Training-Burn belly fat,"
SELECT
    Translated_Review
FROM
    reviews
WHERE
    App = 'Abs Training-Burn belly fat'
    AND Sentiment = 'Neutral';

--all the negative sentiment reviews for Adobe Acrobat Reader from the "cleaned_reviews_db" table, along with their sentiment polarity and sentiment subjectivity,
SELECT
    Translated_Review,
    Sentiment_Polarity,
    Sentiment_Subjectivity
FROM
    reviews
WHERE
    App = 'Adobe Acrobat Reader'
    AND Sentiment = 'Negative';
